name: debian

on:
  push:
    branches:
      - master

jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          ROS_DISTRO: humble
          DEB_DISTRO: jammy
          GITHUB_TOKEN: ${{ secrets.DEBIAN_TOKEN }}