name: devel

on:
  pull_request:
    branches:
      - devel
  push:
    branches:
      - devel

jobs:
  test_docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - humble

        include:
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}
    steps:

      - name: setup ROS environment
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget python3-vcstool python3-pytest libfl-dev pip python3-rosdep build-essential
          sudo pip install unified-planning unified-planning[engines]

      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.6
        with:
          package-name: up4ros2 up_msgs
          target-ros2-distro: humble
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/main/index.yaml

      - uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          files: ${{steps.test-and-coverage.outputs.coverage_file}}
          fail_ci_if_error: false